import Head from 'next/head';
import Image from 'next/image';
import { Inter, Mitr, Montserrat_Alternates } from 'next/font/google';
import Script from 'next/script'
import Avatar from '../assets/img/Avatar.png';
import Github from '../assets/img/Github.png';
import GithubAzul from '../assets/img/GithubAzul.png';
import Linkedin from '../assets/img/Linkedin.png'
import LinkedinAzul from '../assets/img/LinkedinAzul.png'
// import Digibank from '../assets/img/digibankPort.png';
import backLanguages from '../assets/img/backLanguages.png';
import styles from '@/assets/styles/home.module.scss';
import Header from '../components/Header';
import TextShpere from '@/components/TextShpere';
import { useState, useEffect } from 'react';
import Link from 'next/link';
import { sendContactForm } from '@/lib/api';
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

// const inter = Inter({ subsets: ['latin'] })
const mitrR = Mitr({
  weight: "400",
  subsets:['latin']
})
const mitrSB = Mitr({
  weight: "600",
  subsets:['latin']
})
const montserrat = Montserrat_Alternates({ 
  weight: "700",
  subsets: ['latin'] 
})
const montserratH2 = Montserrat_Alternates({ 
  weight: "600",
  subsets: ['latin'] 
})

const initValues = { name: "", email: "", subject: "", message: "" };

const initState = { values: initValues };

export default function Home() {
  const [state, setState] = useState(initState);
  const notify = () => toast("Message Sent!");  
  const {values,} = state;

  const handleChange = ({target}) => 
    setState((prev) =>({
      ...prev,
      values: {
        ...prev.values,
        [target.name]: target.value,
      },
}))

  const onSubmit = async (event) => {
    setState((prev) => ({
      ...prev,
    }));

    try {
      await sendContactForm(values);
      event.preventDefault()
      
      console.log("Botão Clicado!")
      setState(initState)
      
    } catch (error) {
      setState((prev) => ({
        ...prev,
        error: error.message,
      }));
  
    }
  }

  useEffect(() => {
    let constrain = 20;
    let mouseOverContainer = document.getElementById("ex1");
    let ex1Layer = document.getElementById("ex1-layer");
  
    function transforms(x, y, el) {
        let avatar = el.getBoundingClientRect();
        let calcX = -(y - avatar.y - (avatar.height / 2)) / constrain;
        let calcY = (x - avatar.x - (avatar.width / 2)) / constrain;
      
        return "perspective(100px) "
          + "   rotateX("+ calcX +"deg) "
          + "   rotateY("+ calcY +"deg) ";
    };
    
    function transformElement(el, xyEl) {
        el.style.transform  = transforms.apply(null, xyEl);
    }
    
    mouseOverContainer.onmousemove = function(e) {
        let xy = [e.clientX, e.clientY];
        let position = xy.concat([ex1Layer]);
    
        window.requestAnimationFrame(function(){
          transformElement(ex1Layer, position);
        });
    };
  })
  return (
    <>
      {/* <Script type="module" src="followMouse.js"></Script> */}
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <p className={`${styles.backTextWeb} ${mitrSB.className}`}>web developer</p>
      <main className={`${styles.main} ${styles.container} 'scrollspy-example'`} data-bs-spy="scroll" data-bs-target="#redirect"
        data-bs-offset="0" data-bs-smooth-scroll="true" tabIndex="0" >
          <ToastContainer
            position="top-right"
            autoClose={2000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
        <section className={styles.introSection}>
          <Image className={styles.backLanguages} src={backLanguages} alt='Languages Background' />
          <div id='ex1' className={styles.boxTop}>
            <h1 className={`${styles.title} ${montserrat.className}`}>frontend, backend & design</h1>
            <p className={`${styles.myDescription} ${mitrR.className}`}>An Eternal Apprentice, Always Looking to Improve With Creativity</p>
            <Image id='ex1-layer' className={styles.avatar} src={Avatar} alt='Avatar' />
          </div>
          <a href='#scroll1' className={`${styles.defaultBtn} ${mitrR.className}`}>view more</a>
        </section>
        <section className={`${styles.aboutMeSection} ${styles.anime}`} id='scroll1'>
          <p className={`${styles.backTextAbout} ${mitrSB.className}`}>About</p>
          <div className={styles.aboutLeft}>
            <h2 className={`${styles.titleAbout} ${montserratH2.className}`}>
              Hi,
            </h2>
            <h2 className={`${styles.titleAbout} ${montserratH2.className}`}>
              I`m Matheus
            </h2>
            <p className={`${styles.paragraphAbout} ${mitrR.className}`}>A full-stack developer always willing to learn more about this beautiful area of ​​programming.</p>
            <p className={`${styles.paragraphAbout} ${mitrR.className}`}>In search of my first big job, I took many courses and learned several programming languages</p>
          </div>
          <div className={styles.aboutRight}>
            <TextShpere />
          </div>
        </section>
        <section className={styles.projectsSection} id='scroll2'>
          <p className={`${styles.backTextProject} ${mitrSB.className}`}>portfolio</p>
          <div className={styles.textsProjects}>
            <h2 className={`${styles.titleProject} ${montserratH2.className}`}>my projects</h2>
            <p className={`${styles.paragraphProjects} ${mitrR.className}`}>to acquire knowledge in this area, I developed some projects alone and in  groups that simulated real problems.</p>
          </div>
          <div className={styles.myProjects}>
            <div className={styles.cardProject}>
              {/* <Image src={Digibank} alt='digibank portfolio' /> */}
            </div>
            <div className={styles.cardProject}>
              {/* <Image src={Digibank} alt='digibank portfolio' /> */}
            </div>
            <div className={styles.cardProject}>
              {/* <Image src={Digibank} alt='digibank portfolio' /> */}
            </div>
          </div>
        </section>
        <section className={styles.contactSection} id='scroll3'>
          <p className={`${styles.backTextContact} ${mitrSB.className}`}>contact</p>
          <div className={styles.leftContact}>
            <h2 className={`${styles.titleContact} ${montserratH2.className}`}>contact me</h2>
            <form className={styles.formArea}>
              <div className={styles.nameEmail}>
                <div className={styles.orgInput}>
                  <label className={mitrR.className}>name</label>
                  <input 
                  type="text" 
                  name='name' 
                  className={styles.smallInput} 
                  value={values.name} 
                  onChange={handleChange}></input>
                </div>
                <div className={styles.orgInput}>
                  <label className={mitrR.className}>email</label>
                  <input type="email" name='email' className={styles.smallInput} value={values.email} 
                  onChange={handleChange}></input>
                </div>
              </div>
              <label className={mitrR.className}>subject</label>
              <input type="text" name='subject' className={styles.largeInput} value={values.subject} 
                  onChange={handleChange}></input>
              <label className={mitrR.className}>message</label>
              <textarea name='message' className={styles.textAreaContact} value={values.message} 
                  onChange={handleChange}></textarea>
              <button  className={styles.btnSend} onClick={onSubmit} type="submit">submit</button>
            </form>
          </div>
          <div className={styles.rightContact}>
            <Link className={styles.bottomGithub} href="https://github.com/Leal-Matheus"><Image src={Github} alt="github logo"/></Link>
            <Link className={styles.topGithub} href="https://github.com/Leal-Matheus"><Image src={GithubAzul} alt="github logo"/></Link>
            <Link className={styles.bottomLinkedin} href="https://www.linkedin.com/in/matheus-leal-palmuti-b94009240/"><Image src={Linkedin} alt="linkedin logo"/></Link>
            <Link className={styles.topLinkedin} href="https://www.linkedin.com/in/matheus-leal-palmuti-b94009240/"><Image src={LinkedinAzul} alt="linkedin logo"/></Link>
          </div>
        </section>
      </main>
    </>
  )
}
