import Head from 'next/head';
import Image from 'next/image';
import { Inter, Mitr, Montserrat_Alternates } from 'next/font/google';
import Avatar from '../assets/img/Avatar.png';
import backLanguages from '../assets/img/backLanguages.png';
import styles from '@/assets/styles/home.module.scss';
import Header from '../components/Header';

// const inter = Inter({ subsets: ['latin'] })
const mitrR = Mitr({
  weight: "400",
  subsets:['latin']
})
const mitrSB = Mitr({
  weight: "600",
  subsets:['latin']
})
const montserrat = Montserrat_Alternates({ 
  weight: "700",
  subsets: ['latin'] 
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <p className={`${styles.backText} ${mitrSB.className}`}>web developer</p>
      <main className={styles.main}>
        <Image className={styles.backLanguages} src={backLanguages} alt='Languages Background' />
        <div className={styles.boxTop}>
          <h1 className={`${styles.title} ${montserrat.className}`}>frontend, backend & design</h1>
          <p className={`${styles.myDescription} ${mitrR.className}`}>An Eternal Apprentice, Always Looking to Improve With Creativity</p>
          <Image className={styles.avatar} src={Avatar} alt='Avatar' />
        </div>
        <button className={`${styles.defaultBtn} ${mitrR.className}`}>view more</button>
      </main>
    </>
  )
}
